name: Create Tag on Merge

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - master

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate tag
        run: |
          # Check if the commit message contains #major or #patch
          if [[ $(git log -1 --pretty=%B) =~ "#major|#patch" ]]; then
            # Get the latest tag
            latest_tag=$(git describe --tags --abbrev=0)
            # Increment the tag version
            new_tag=$(echo "$latest_tag" | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
            # Create and push the new tag
            git tag "$new_tag"
            git push origin "$new_tag"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
